from pathlib import Path
path = Path('ADNI三模态.ipynb')
text = path.read_text(encoding='utf-8')
old = "#医学图像\nnii = CNN_3D(num_class=1)\nnii= nii.to(device)\nall_ad = 'ad_nii_KG/'\nall_normal = 'normal_nii_kg/'\nall_mci = 'NC_nii_kg/'\ndataset = NiiDataset(all_ad)\nbatch_size = 16\ndataloader = DataLoader(dataset, batch_size=batch_size, shuffle=False)\nall_outputs = []\nfor batch_idx, batch_data in enumerate(dataloader):\n    batch_data = batch_data.to(device)\n    output = nii(batch_data)\n    all_outputs.append(output)\nad_output = torch.cat(all_outputs, dim=0)\n\ndataset = NiiDataset(all_normal)\ndataloader = DataLoader(dataset, batch_size=batch_size, shuffle=False)\nall_outputs = []\nfor batch_idx, batch_data in enumerate(dataloader):\n    batch_data = batch_data.to(device)\n    output = nii(batch_data)\n    all_outputs.append(output)\nnormal_output = torch.cat(all_outputs, dim=0)\n\ndataset = NiiDataset(all_mci)\ndataloader = DataLoader(dataset, batch_size=batch_size, shuffle=False)\nall_outputs = []\nfor batch_idx, batch_data in enumerate(dataloader):\n    batch_data = batch_data.to(device)\n    output = nii(batch_data)\n    all_outputs.append(output)\nmci_output = torch.cat(all_outputs, dim=0)\n"
new = "#医学图像\nnii = CNN_3D(num_class=1)\nnii = nii.to(device)\nall_ad = 'ad_nii_KG/'\nall_normal = 'normal_nii_kg/'\nall_mci = 'NC_nii_kg/'\n\n# 打印原始 NIfTI tensor 形状，确保 MRI 提取的 nii.shape 可见\n\ndef print_raw_nii_shape(folder, label):\n    dataset = NiiDataset(folder)\n    if len(dataset) == 0:\n        print(f'{label} raw nii tensor shape---> empty dataset')\n        return\n    print(f'{label} raw nii tensor shape--->', dataset[0].shape)\n\nprint_raw_nii_shape(all_ad, 'ad')\nprint_raw_nii_shape(all_normal, 'normal')\nprint_raw_nii_shape(all_mci, 'mci')\n\ndataset = NiiDataset(all_ad)\nbatch_size = 16\ndataloader = DataLoader(dataset, batch_size=batch_size, shuffle=False)\nall_outputs = []\nfor batch_idx, batch_data in enumerate(dataloader):\n    batch_data = batch_data.to(device)\n    output = nii(batch_data)\n    all_outputs.append(output)\nad_output = torch.cat(all_outputs, dim=0)\n\ndataset = NiiDataset(all_normal)\ndataloader = DataLoader(dataset, batch_size=batch_size, shuffle=False)\nall_outputs = []\nfor batch_idx, batch_data in enumerate(dataloader):\n    batch_data = batch_data.to(device)\n    output = nii(batch_data)\n    all_outputs.append(output)\nnormal_output = torch.cat(all_outputs, dim=0)\n\ndataset = NiiDataset(all_mci)\ndataloader = DataLoader(dataset, batch_size=batch_size, shuffle=False)\nall_outputs = []\nfor batch_idx, batch_data in enumerate(dataloader):\n    batch_data = batch_data.to(device)\n    output = nii(batch_data)\n    all_outputs.append(output)\nmci_output = torch.cat(all_outputs, dim=0)\n"
if old not in text:
    raise SystemExit('Old block not found')
path.write_text(text.replace(old, new), encoding='utf-8')
print('patched')
